title: Tintswalo Macebele 
logo: /images/images/profile2.jpg
description: UCT Mechatronics Engineering Graduate | Aspiring Project Engineer
#show_downloads: true
#resume: reports/Tintswalo_Resume.pdf
google_analytics:
theme: jekyll-theme-minimal
